import './styles.css';
import { getUser, logout, handleAuthCallback } from '@netlify/identity';
const app=document.querySelector('#admin-app');
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const state={user:null,bank:null,status:null,stats:null,filter:{type:'',exam:'',group:'',subject:'',status:'',q:'',offset:0}};
async function api(path,options={}){const r=await fetch(`/api/${path}`,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||d.detail||`HTTP ${r.status}`);return d}
async function init(){try{if(location.hash)await handleAuthCallback()}catch{}state.user=await getUser();if(!state.user){app.innerHTML=deny('請先從考生端登入，再使用管理後台。');return}try{await api('published-status')}catch(e){app.innerHTML=deny('此帳號沒有管理權限。請在 Netlify Identity 將您的帳號設定為 admin role，或在環境變數 ADMIN_EMAILS 加入您的 Email。');return}await loadAll();render();}
function deny(msg){return `<div class="container" style="padding:70px 20px"><div class="panel"><h2>管理後台</h2><div class="notice danger">${esc(msg)}</div><a class="btn btn-primary" href="/">回考生端</a></div></div>`}
async function loadAll(){const qs=new URLSearchParams({...state.filter,limit:'100'});[state.bank,state.status,state.stats]=await Promise.all([api(`admin-bank?${qs}`),api('sync-status'),api('admin-stats').catch(()=>({summary:{},hardest:[],subjects:[]}))]);}
function render(){const b=state.bank,s=b.summary,p=b.published||{};app.innerHTML=`
<header class="topbar"><div class="container topbar-inner"><div class="brand"><img class="brand-logo" src="/logos/cnu.png"><img class="brand-logo lab-logo" src="/logos/atib.png"><div>ATIB 題庫管理後台<small>Draft → Review → Publish</small></div></div><div class="nav-actions"><a class="btn btn-ghost btn-sm" href="/">考生端</a><button id="logout" class="btn btn-ghost btn-sm">登出</button></div></div></header>
<main><section class="hero"><div class="container"><h1>只有管理者可以修改，<span class="accent">考生只看已發布版本。</span></h1><p>所有同步、匯入、修改先進入「草稿題庫」。您確認答案、分類與來源後，勾選「核准發布」，最後按一次「發布考生版」。未核准或待複核題目不會出現在考生網站。</p></div></section>
<section class="section"><div class="container"><div class="admin-grid">${card('草稿總題數',s.total)}${card('學科草稿',s.byType?.academic||0)}${card('術科草稿',s.byType?.practical||0)}${card('目前已發布',p.summary?.total||0)}</div></div></section>
<section class="section"><div class="container"><div class="panel"><div class="toolbar"><div><h2 style="margin:0">發布控制</h2><div class="small">最後發布：${esc(p.publishedAt||'尚未發布')}</div></div><span class="spacer"></span><button id="publishBtn" class="btn btn-primary">發布考生版</button></div><div class="notice info">發布不是把後台開放給考生，而是把「已核准」題目複製成唯讀的正式題庫快照。考生端永遠讀取上一個正式快照。</div><div class="count-table">${Object.entries(s.bySubject||{}).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="count-chip"><b>${v}</b>${esc(k)}</div>`).join('')}</div></div></div></section>
<section class="section"><div class="container"><div class="panel"><div class="section-title"><div><h2>草稿題庫編輯</h2><p>不確定的題目請保留「待複核」，修正完成後再核准。</p></div></div>${filtersHTML(b)}<div id="questionList">${(b.items||[]).map(questionCard).join('')||'<div class="notice">沒有符合條件的題目。</div>'}</div>${b.totalFiltered>100?`<div class="setup-actions"><button id="nextPage" class="btn btn-secondary">下一批 100 題</button></div>`:''}</div></div></section>
<section class="section"><div class="container"><div class="panel"><div class="section-title"><div><h2>官方來源同步</h2><p>同步只會進草稿，不會直接公開。</p></div></div><div class="notice">主要歷屆入口：運動部歷屆考題；現有解析器仍保留 TATS 直接 PDF 作為備援。官方更正公告優先於原答案。</div>${(state.status?.sources||[]).map(sourceCard).join('')}</div></div></section>
<section class="section"><div class="container"><div class="panel"><div class="section-title"><div><h2>人工題庫匯入</h2><p>適合掃描檔、人工校正題或您自行修改後的 JSON。</p></div></div><div class="field"><label>JSON（{ "items": [...] }）</label><textarea id="importJson" rows="7"></textarea></div><div class="setup-actions"><button id="importBtn" class="btn btn-secondary">匯入到草稿</button></div><div id="importMsg"></div></div></div></section>
<section class="section"><div class="container"><div class="panel"><div class="section-title"><div><h2>考生錯題統計</h2></div></div>${statsHTML()}</div></div></section></main>
<div id="modalRoot"></div>`;
 bind();}
function card(label,val){return `<div class="stat-card"><strong>${esc(val??0)}</strong><span>${esc(label)}</span></div>`}
function filtersHTML(b){const f=state.filter;return `<div class="form-grid"><div class="field"><label>類型</label><select id="fType"><option value="">全部</option><option value="academic" ${f.type==='academic'?'selected':''}>學科</option><option value="practical" ${f.type==='practical'?'selected':''}>術科</option></select></div><div class="field"><label>年度/梯次</label><select id="fExam"><option value="">全部</option>${(b.filters.exams||[]).map(x=>`<option ${f.exam===x?'selected':''}>${esc(x)}</option>`).join('')}</select></div><div class="field"><label>考科/技能</label><select id="fSubject"><option value="">全部</option>${(b.filters.subjects||[]).map(x=>`<option ${f.subject===x?'selected':''}>${esc(x)}</option>`).join('')}</select></div><div class="field"><label>驗證狀態</label><select id="fStatus"><option value="">全部</option>${(b.filters.statuses||[]).map(x=>`<option ${f.status===x?'selected':''}>${esc(x)}</option>`).join('')}</select></div><div class="field field-full"><label>搜尋題號、題幹、來源或註記</label><input id="fQ" value="${esc(f.q)}" placeholder="例如 114-1、Lachman、Q94、運動營養"></div></div><div class="setup-actions"><button id="filterBtn" class="btn btn-secondary">套用篩選</button><button id="resetBtn" class="btn btn-secondary">清除</button><button id="bulkApprove" class="btn btn-primary">批次核准目前篩選</button><button id="bulkUnapprove" class="btn btn-secondary">批次取消核准</button></div><div class="small">符合 ${b.totalFiltered} 題；目前顯示 ${b.items.length} 題。</div>`}
function questionCard(q){const title=q.type==='academic'?`${q.number?`Q${q.number} `:''}${q.text||''}`:q.title||q.prompt;const errs=q.publishErrors||[];return `<div class="question-admin-card"><div class="question-admin-meta"><span class="badge">${q.type==='academic'?'學科':'術科'}</span><span class="badge">${esc(q.exam)}</span><span class="badge">${esc(q.group)}</span><span class="badge">${esc(q.subject)}</span><span class="badge ${q.approvedForPublish?'official':''}">${q.approvedForPublish?'已核准':'未核准'}</span></div><h4>${esc(title).slice(0,260)}</h4><div class="source-mini">${esc(q.sourceUrl||'無來源')}</div>${errs.length?`<div class="publish-errors">不可發布：${errs.map(esc).join('、')}</div>`:'<div class="publish-ok">✓ 可進入下一次發布</div>'}<div class="setup-actions"><button class="btn btn-secondary btn-sm" data-edit="${esc(q.id)}">編輯 / 核對</button></div></div>`}
function sourceCard(s){const m=s.meta;return `<div class="source-card"><div><h4>${esc(s.label)}</h4><p>${esc(s.key)}｜${esc(s.parseMode)}${m?`｜最近匯入 ${m.itemCount||0} 題`:''}</p></div><button class="btn btn-secondary btn-sm" data-sync="${esc(s.key)}" ${s.status==='manual-review-required'?'disabled':''}>${s.status==='manual-review-required'?'需人工複核':'同步到草稿'}</button></div>`}
function statsHTML(){const r=state.stats||{};return `<div class="admin-grid">${card('練習份數',r.summary?.attempts||0)}${card('考生人數',r.summary?.users||0)}${card('已計分作答',r.summary?.totalScored||0)}${card('整體正確率',r.summary?.accuracy==null?'—':Math.round(r.summary.accuracy*100)+'%')}</div><div class="table-wrap" style="margin-top:16px"><table class="data-table"><thead><tr><th>年度</th><th>考科</th><th>題目</th><th>作答</th><th>答錯</th><th>錯誤率</th></tr></thead><tbody>${(r.hardest||[]).slice(0,50).map(x=>`<tr><td>${esc(x.exam)}</td><td>${esc(x.subject)}</td><td>${esc(x.text)}</td><td>${x.attempts}</td><td>${x.wrong}</td><td>${Math.round((x.errorRate||0)*100)}%</td></tr>`).join('')||'<tr><td colspan="6">尚無作答資料</td></tr>'}</tbody></table></div>`}
function bind(){document.querySelector('#logout').onclick=async()=>{await logout();location.href='/'};document.querySelector('#filterBtn').onclick=async()=>{state.filter={type:fType.value,exam:fExam.value,group:'',subject:fSubject.value,status:fStatus.value,q:fQ.value,offset:0};await loadAll();render()};document.querySelector('#resetBtn').onclick=async()=>{state.filter={type:'',exam:'',group:'',subject:'',status:'',q:'',offset:0};await loadAll();render()};document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editQuestion(b.dataset.edit));document.querySelectorAll('[data-sync]').forEach(b=>b.onclick=()=>syncSource(b));document.querySelector('#publishBtn').onclick=publish;document.querySelector('#bulkApprove').onclick=()=>bulk('approve');document.querySelector('#bulkUnapprove').onclick=()=>bulk('unapprove');document.querySelector('#importBtn').onclick=importJson;document.querySelector('#nextPage')?.addEventListener('click',async()=>{state.filter.offset=(state.filter.offset||0)+100;await loadAll();render()});}
function editQuestion(id){const q=state.bank.items.find(x=>x.id===id);if(!q)return;const academic=q.type==='academic';modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal" style="width:min(920px,100%);max-height:92vh;overflow:auto"><h2>編輯題目</h2><div class="editor-grid"><div class="field"><label>年度/梯次</label><input id="eExam" value="${esc(q.exam)}"></div><div class="field"><label>原題號</label><input id="eNum" type="number" value="${esc(q.number??'')}"></div><div class="field"><label>類群</label><input id="eGroup" value="${esc(q.group)}"></div><div class="field"><label>考科/技能</label><input id="eSubject" value="${esc(q.subject)}"></div>${academic?`<div class="field wide"><label>題幹</label><textarea id="eText" rows="4">${esc(q.text)}</textarea></div><div class="field wide"><label>選項（A-D）</label><div class="option-grid">${['A','B','C','D'].map(k=>`<input id="opt${k}" placeholder="${k}" value="${esc(q.options?.[k]||'')}">`).join('')}</div></div><div class="field"><label>正確答案（可用 A,D；送分填 BONUS）</label><input id="eAns" value="${esc((q.acceptedAnswers||[]).join(','))}"></div><div class="field"><label>答案驗證狀態</label><select id="eStatus">${['needs-review','official-pdf','official-corrected','official-bonus','manual-reviewed'].map(x=>`<option ${q.verificationStatus===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field wide"><label>考生版解析</label><textarea id="eExplanation" rows="5">${esc(q.explanation||'')}</textarea></div>`:`<div class="field wide"><label>術科題目</label><textarea id="eTitle" rows="2">${esc(q.title||'')}</textarea></div><div class="field wide"><label>實作要求</label><textarea id="ePrompt" rows="4">${esc(q.prompt||'')}</textarea></div><div class="field wide"><label>教學參考答案</label><textarea id="eExplanation" rows="6">${esc(q.explanation||'')}</textarea></div>`}<div class="field wide"><label>題目來源 URL</label><input id="eSource" value="${esc(q.sourceUrl||'')}"></div>${academic?`<div class="field wide"><label>答案來源 URL</label><input id="eAnswerSource" value="${esc(q.answerSource||'')}"></div>`:''}<div class="field wide"><label>學理/解析來源</label><input id="eExplanationSource" value="${esc(q.explanationSource||'')}"></div><div class="field wide"><label>管理者複核註記</label><textarea id="eNotes" rows="3">${esc(q.reviewNotes||'')}</textarea></div><div class="field"><label><input id="eEnabled" type="checkbox" ${q.enabled!==false?'checked':''}> 啟用此題</label></div><div class="field"><label><input id="eApproved" type="checkbox" ${q.approvedForPublish?'checked':''}> 我已核對，核准發布</label></div></div><div id="editMsg"></div><div class="modal-actions"><button id="closeEdit" class="btn btn-secondary">取消</button><button id="saveEdit" class="btn btn-primary">儲存草稿</button></div></div></div>`;closeEdit.onclick=()=>modalRoot.innerHTML='';saveEdit.onclick=()=>saveEditQuestion(q,academic);}
async function saveEditQuestion(q,academic){const x={...q,exam:eExam.value.trim(),number:eNum.value?Number(eNum.value):null,group:eGroup.value.trim(),subject:eSubject.value.trim(),sourceUrl:eSource.value.trim(),explanationSource:eExplanationSource.value.trim(),reviewNotes:eNotes.value.trim(),enabled:eEnabled.checked,approvedForPublish:eApproved.checked,explanation:eExplanation.value.trim()};if(academic){x.text=eText.value.trim();x.options={A:optA.value.trim(),B:optB.value.trim(),C:optC.value.trim(),D:optD.value.trim()};x.acceptedAnswers=eAns.value.split(',').map(v=>v.trim().toUpperCase()).filter(Boolean);x.verificationStatus=eStatus.value;x.answerSource=eAnswerSource.value.trim()}else{x.title=eTitle.value.trim();x.prompt=ePrompt.value.trim()}try{await api('admin-question',{method:'POST',body:JSON.stringify({question:x})});modalRoot.innerHTML='';await loadAll();render()}catch(e){editMsg.innerHTML=`<div class="notice danger">${esc(e.message)}</div>`}}
async function syncSource(btn){btn.disabled=true;btn.textContent='同步中…';try{const d=await api('sync-official',{method:'POST',body:JSON.stringify({key:btn.dataset.sync})});alert(`已匯入草稿 ${d.imported||0} 題。尚未公開。`);await loadAll();render()}catch(e){alert(e.message);btn.disabled=false;btn.textContent='同步到草稿'}}
async function bulk(action){if(!confirm(action==='approve'?'將目前篩選條件內、內容與來源完整的題目批次核准？待複核題會自動跳過。':'取消目前篩選條件內題目的發布核准？'))return;try{const d=await api('admin-bulk',{method:'POST',body:JSON.stringify({action,filter:state.filter})});alert(`完成：處理 ${d.touched} 題，跳過 ${d.skipped||0} 題。`);await loadAll();render()}catch(e){alert(e.message)}}
async function publish(){if(!confirm('確定將所有「已核准發布」且驗證完整的題目發布給考生？未核准與待複核題會被排除。'))return;try{const d=await api('publish-bank',{method:'POST',body:'{}'});alert(`發布完成：${d.summary.total} 題；另有 ${d.blockedCount} 題留在草稿。`);await loadAll();render()}catch(e){alert(e.message)}}
async function importJson(){const box=document.querySelector('#importMsg');try{const raw=JSON.parse(document.querySelector('#importJson').value);const d=await api('import-bank',{method:'POST',body:JSON.stringify({items:raw.items||[]})});box.innerHTML=`<div class="notice success">已匯入草稿：新增 ${d.added}、更新 ${d.updated}、總數 ${d.total}。</div>`;await loadAll();render()}catch(e){box.innerHTML=`<div class="notice danger">${esc(e.message)}</div>`}}
init();
